/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.lab4inf.mxr.math;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.function.DoubleFunction;
import java.util.function.Function;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


class DifferentiatorTest {
	
	MXRFunction sinFunc = (x) -> Math.sin(x);
	MXRFunction cosFunc = (x) -> Math.cos(x);
	
	@BeforeEach
	void setUp() throws Exception {
		
	}
	
    @Test
    void dummyTest() {
    	
    	MXRFunction sinFunc = (x) -> Math.sin(x);
    	
    	double result, expected, eps=2*Differentiator.EPS, x = 1.5;
  
    	expected = cosFunc.eval(x);
    	
    	result = Differentiator.diff(sinFunc, x, eps);
    	
    	assertEquals(expected, result, eps);
    }
}
