/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_lab4inf_mxr_math_Differentiator */

#ifndef _Included_de_lab4inf_mxr_math_Differentiator
#define _Included_de_lab4inf_mxr_math_Differentiator
#ifdef __cplusplus
extern "C" {
#endif
#undef de_lab4inf_mxr_math_Differentiator_EPS
#define de_lab4inf_mxr_math_Differentiator_EPS 5.0E-10
/*
 * Class:     de_lab4inf_mxr_math_Differentiator
 * Method:    diff
 * Signature: (Lde/lab4inf/mxr/math/MXRFunction;DD)D
 */
JNIEXPORT jdouble JNICALL Java_de_lab4inf_mxr_math_Differentiator_diff
  (JNIEnv *, jclass, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
